name: CI
permissions:
  contents: write

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check version bump
        if: github.event_name == 'pull_request'
        run: |
          git fetch origin main
          MAIN=$(jq -r .version <(git show origin/main:package.json))
          PR=$(jq -r .version package.json)
          if [ "$(printf '%s\n%s\n' "$MAIN" "$PR" | sort -V | head -n1)" = "$PR" ]; then
            echo "Version must be bumped: PR ($PR) ≤ main ($MAIN)"
            exit 1
          fi

  build:
    needs: version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.package.outputs.version }}
      vsix-path: ${{ steps.package.outputs.vsix }}
      vsix-name: ${{ steps.package.outputs.name }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Compile TypeScript
        run: npm run compile

      - name: Install VSCE CLI
        run: npm install --global @vscode/vsce

      - name: Build & Package Extension
        id: package
        run: |
          npm install --global @vscode/vsce

          # 1. Compile and bundle
          npm run compile
          npm run bundle

          # 2. Remove all original JS outputs, keep only the bundle
          find out -type f -name "*.js" ! -name "extension.bundle.js" -delete

          # 3. Package VSIX
          mkdir -p dist
          vsce package -o dist/${npm_package_name}-${npm_package_version}.vsix

          # 4. Set outputs
          NAME=$(jq -r .name package.json)
          VERSION=$(jq -r .version package.json)
          VSIX_PATH="dist/${NAME}-${VERSION}.vsix"
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          echo "vsix=${VSIX_PATH}"  >> $GITHUB_OUTPUT
          echo "name=${NAME}-${VERSION}.vsix" >> $GITHUB_OUTPUT
        env:
          CI: true

          CI: true

      - uses: actions/upload-artifact@v4
        with:
          name: vsix
          path: ${{ steps.package.outputs.vsix }}

  release:
    if: github.event_name == 'push'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: vsix
          path: dist/

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: v${{ needs.build.outputs.version }}
          release_name: v${{ needs.build.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload VSIX to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ needs.build.outputs.vsix-path }}
          asset_name: ${{ needs.build.outputs.vsix-name }}
          asset_content_type: application/octet-stream
